#! /bin/sh

if test -d fw/bin
  then
    PATH="`pwd`/fw/bin:$PATH"
    export PATH
  fi

fwb=`which fw-bootstrap`

if test -z "$fwb"
  then
    echo "bootstrap: fatal: fw-bootstrap not installed or not in PATH" 1>&2
    exit 1
  fi

"$fwb" --fw_version "0.3.1" --name fw-template-erlang-rebar --revision svn --template fw-template --template_type erlang-rebar --svn_project_path https://fwtemplates.googlecode.com/svn/trunk/fw-template-erlang-rebar --svn_tag_root https://fwtemplates.googlecode.com/svn/tags/fw-template-erlang-rebar "$@"
